config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'games#index'
  get '/archive', to: 'games#archive'
  get '/leaderboard', to: 'games#leaderboard'
  get '/users/:id/history', to: 'users#history', as: 'user_history'
  resources :games
  resource :pizza_config
  resources :saved_orders
  resources :product, only: :show

  post '/product(/:id)', to: 'product#add_to_saved_order'
  get '/pizza', to: 'pizza_orders#new'
  post '/pizza', to: 'pizza_orders#create'
  get '/pizza/random', to: 'pizza_orders#random_order'
  get '/pizza/create', to: 'pizza_orders#create_pizza'
  get '/pizza/checkout', to: 'pizza_orders#checkout'
  get '/pizza/checkout_confirm', to: 'pizza_orders#checkout_confirm'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, uniqueness: true
  has_many :players
  has_one :pizza_config
  has_many :saved_orders

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  require 'owner_stats.rb'

  def history
    @user = User.find(params[:id])
    @stats = OwnerStats.new(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/history.html.erb
<div class="container">
  <div class="span5 offset2">
    <div class="page-header">
      <h1><%= "#{@user.name}'s History" %></h1>
    </div>

    <% if @stats.win_perc.nil? %>
      <p>No history to display.</p>
    <% else %>

      <table class="table">
        <tr>
          <th></th>
          <th>Win Rate</th>
          <th>Average Round Out</th>
          <th>Average Percent of Total Chips when going out</th>
        </tr>
        <tr>
          <td></td>
          <td><%= @stats.win_perc.round(0) %>%</td>
          <td><%= @stats.round_out_average.round(2) %></td>
          <td><%= @stats.chips_out_perc.round(2) %>%</td>
        </tr>
      </table>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Game Name</th>
            <th>Game Winner</th>
            <th>Player Standing</th>
            <th>Percent of Total Chips Small Blind is when going out</th>
          </tr>
        </thead>
        <tbody>

          <% @stats.players.each do |player| %>
            <tr>
              <td><%= link_to player.game.name, game_path(player.game), class: "btn btn-default" %></td>
              <td><%= player.game.winner.owner.name %></td>
              <% player_stats = @stats.player_stats(player) %>
              <% if player_stats[:winner] == true %>
                <td>Winner</td>
                <td></td>
              <% else %>
                <td><%= "Went out on round #{player_stats[:round_out]+1}" %></td>
                <td><%= "#{player_stats[:chips_perc].round(2)}%" %></td>
              <% end %>
            </tr>
          <% end %>

        </tbody>
      </table>

    <% end %>

  </div>
</div>