config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'games#index'
  get '/archive', to: 'games#archive'
  get '/leaderboard', to: 'games#leaderboard'
  get '/users/:id/history', to: 'users#history', as: 'user_history'
  resources :games
  resource :pizza_config
  resources :saved_orders
  resources :product, only: :show

  post '/product(/:id)', to: 'product#add_to_saved_order'
  get '/pizza', to: 'pizza_orders#new'
  post '/pizza', to: 'pizza_orders#create'
  get '/pizza/random', to: 'pizza_orders#random_order'
  get '/pizza/create', to: 'pizza_orders#create_pizza'
  get '/pizza/checkout', to: 'pizza_orders#checkout'
  get '/pizza/checkout_confirm', to: 'pizza_orders#checkout_confirm'
end

app/models/pizza_order.rb
class PizzaOrder < ActiveRecord::Base
  require 'mechanize'

  serialize :checkout_info, Array

  belongs_to :cart
  belongs_to :pizzapage

  def add_cart_to_web_cart
    mech = Mechanize.new()
    self.cart.product_orders.each do |product_order|
      product_page = mech.get(product_order.product.url)
      form = product_page.form('crtitmfrm')

      (product_order.options[:radios] || []).each do |name, selection|
        radio = form.radiobuttons.detect {|r| r.name == name && r.text == selection}
        radio.click unless radio.nil? or radio.checked == true
      end

      (product_order.options[:checkboxes] || []).each do |name, selections|
        selections.each do |selection|
          checkbox = form.checkboxes.detect {|c| c.name == name && c.text == selection}
          checkbox.click
        end
      end

      (product_order.options[:text_fields] || []).each do |name, value|
        text_field = form.fields.detect {|f| f.name == name}
        text_field.value = value
      end

      form.submit

    end
    checkout_page = mech.get(self.pizzapage.checkout_url)
    self.checkout_info = checkout_page.search("//td[starts-with(font, '$') or starts-with(font, '($')]").map do |td|
      td.parent.search(".//font[@color='#000000' or @color='#95221d']").to_html.gsub(/\t|\n|<i>|<\/i>|<b>|<\/b>|<\/font>$| color=\"#000000\"| color=\"#95221d\"|<a href=\".*\">|<\/a>|[  ]{2,}/, '').gsub(/^<font>/, "").split("</font><font>")
    end
    self.total = checkout_page.search("//font[starts-with(b, '$')]/b").text.gsub(/\$|\./, "").to_i/100.0
    checkout_page.form('crtordlfrm').field('action_ith').value = "chkoutb"
    checkout_page = checkout_page.form('crtordlfrm').submit
    checkout_page = checkout_page.link.click
    mech.cookie_jar.save(self.cookiespath, session: true)
    self.save
  end

  def proceed_to_checkout(order_info, delivery_info)
    mech = Mechanize.new()
    mech.cookie_jar.load(self.cookiespath)
    checkout_page = mech.get('https://secure1.securebrygid.com/zgrid/proc/site/secure/crtchkoutb.jsp')
    order_info.merge!(delivery_info) unless checkout_page.search("//td[starts-with(font, 'Delivery')]/font").empty?
    form = checkout_page.form
    order_info.each do |name, value|
      form.fields.detect {|f| f.name == name.to_s}.value = value
    end
    puts mech.page.inspect
    form.submit
    puts mech.page.inspect
  end

end

app/controllers/pizza_orders_controller.rb
class PizzaOrdersController < ApplicationController

  before_action :require_login
  before_action :require_config, except: [:new, :create_pizza]

  def new
  end

  def checkout
    @pizza_order = PizzaOrder.find(params[:pizza_order_id])
    @checkout_info = @pizza_order.checkout_info.select {|line| !line.empty?}.each do |line|
      line.unshift("") if line.length == 2
    end
    @config = current_user.pizza_config
  end

  def checkout_confirm
    pizza_order = PizzaOrder.find(params[:pizza_order_id])
    pizza_order.proceed_to_checkout(current_user.pizza_config.order_info,
                                    current_user.pizza_config.delivery_info)
    flash[:alert] = "Pizza Successfully Ordered!"
    if params[:game_id]
      redirect_to game_path(params[:game_id])
    else
      redirect_to pizza_path
    end
  end

  # Create a random pizza order
  def random_order
    # Params: size of pizza, number of pizzas
    # select out pizzas
    size = 2
    qty = 2
    selection = []
    pizzas = get_pizzas
    pizzas.reject! {|pizza| pizza.name == "Create Your Own Pizza"}
    qty.times { selection << pizzas.sample }
    # check we have product options available
    selection.each do |pizza|
      pizza.generate_options if pizza.options == {}
    end
    selection.map! {|pizza| configure_pizza(pizza, size)}.flatten!
    SavedOrder.create(name: "random", user_id: current_user.id, order: selection)
    redirect_to pizza_path
  end

  def create_pizza
    @pizzas = get_pizzas
  end

  private

  def require_login
    unless user_signed_in?
      flash[:alert] = "You must log in to continue"
      redirect_to new_user_session_path
    end
  end

  def require_config
    unless current_user.pizza_config
      flash[:alert] = "You must create a config before you can continue"
      redirect_to root_path
    end
  end

  def get_pizzas
    pizzas = []
    pizza_categories = Category.select {|category| category.name == "classic" || category.name == "premium"}
    pizza_categories.each do |category|
      category.products.each do |product|
        pizzas << product
      end
    end
    pizzas.sort_by! {|pizza| (pizza.options[:checkboxes]["mcctsuids"] || []).length}
  end

  def configure_pizza(pizza, size)
    options = pizza.options
    options.delete(:checkboxes)
    options.delete(:text_fields)
    options[:radios].delete("mcctstids3")
    options[:radios]["olszid"] = options[:radios]["olszid"][size]
    options[:radios]["mcctstids1"] = options[:radios]["mcctstids1"][0]
    options[:radios]["mcctstids2"] = options[:radios]["mcctstids2"][0]
    options[:radios]["otid"] = options[:radios]["otid"][0]
    [pizza.name => options]
  end

end

app/helpers/pizza_orders_helper.rb
module PizzaOrdersHelper
end

app/views/pizza_orders/checkout.html.erb
<div class="content-centered">

  <h1><%= @pizza_order.total %></h1>

  <table class="table table-hover">
    <% @checkout_info.each do |line| %>
      <tr>
        <% line.each do |cell| %>
          <td><%= cell %></td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <h3>Configuration</h3>
  <hr>
  <p><b>Name:</b> <%= "#{@config.first_name} #{@config.last_name}" %></p>
  <p><b>Phone Number:</b> <%= "#{@config.phone_number}" %></p>
  <p><b>Email:</b> <%= "#{@config.email}" %></p>
  <p><b>Order Note:</b> <%= "#{@config.ordernote}" %></p>
  <hr>
  <p><b>Address:</b> <%= "#{@config.address}" %></p>
  <p><b>Company:</b> <%= "#{@config.company}" %></p>
  <p><b>Buzzer:</b> <%= "#{@config.buzzer}" %></p>
  <p><b>City:</b> <%= "#{@config.city}" %></p>
  <p><b>Postal Code:</b> <%= "#{@config.postal_code}" %></p>
  <p><b>Payment Method:</b> <%= "#{@config.payment_method}" %></p>
  <hr>

  <%= link_to "Confirm Submit", pizza_checkout_confirm_path(pizza_order_id: @pizza_order.id, game_id: params[:game_id]), class: "btn btn-primary" %>
</div>

app/views/pizza_orders/create_pizza.html.erb
<div class="content-centered">
  <h1>Create a Pizza</h1>

  <table class="table table-hover" id="pizzas-table">
    <tr>
      <th>Name</th>
      <th>Default Toppings</th>
      <th></th>
    </tr>
  <% @pizzas.each do |pizza| %>
    <tr>
      <td><%= pizza.name %></td>
      <td><%= (pizza.options[:checkboxes]["mcctsuids"] || []).join(", ") if pizza.options[:checkboxes]%></td>
      <td><%= link_to "Select", product_path(pizza.id), class: "btn btn-primary" %></td>
    </tr>
  <% end %>
  </table>
</div>

app/views/pizza_orders/new.html.erb
<div class="container">
  <div class="page-header span5 offset2">
    <h1>Order Pizza</h1>
    <%= link_to "Add a pizza to a new or existing order", pizza_create_path, class: "btn btn-primary" %>
    <% if current_user.pizza_config %>
      <%= link_to "Edit Order Configuration", edit_pizza_config_path, class: "btn btn-primary" %>
    <% else %>
      <%= link_to "You do not currently have an order configurtion, click here to set one", new_pizza_config_path, class: "btn btn-danger" %>
    <% end %>
  </div>
  <div id="random-order-options"></div>
  <div id="saved-orders">
    <% current_user.saved_orders.each do |saved_order| %>
      <div id=<%= "saved-order-#{saved_order.id}" %> class="row">
        <div class="col-xs-3">
          <% if current_user.pizza_config %>
            <%= link_to "Order \"#{saved_order.name}\"", saved_order_path(id: saved_order.id), class: "btn btn-primary" %>
          <% else %>
            <button type="button" class="btn btn-primary" disabled><%= "Order \"#{saved_order.name}\"" %></button>
          <% end %>
        </div>
        <div class="col-xs-9">
          <button type="button" class="btn btn-primary show-order" data-orderid=<%= saved_order.id %>>Show Order</button>
          <%= link_to "Edit order", edit_saved_order_path(id: saved_order.id), class: "btn btn-default" %>
          <%= link_to "Delete order", saved_order_path(id: saved_order.id), class: "btn btn-danger", method: "delete", data: { confirm: "Are you sure?" } %>
        </div>
        <pre class="saved-order" data-orderid=<%= saved_order.id %>><%= saved_order.order.to_yaml %></pre>
      </div>
    <% end %>
  </div>
</div>