config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'games#index'
  get '/archive', to: 'games#archive'
  get '/leaderboard', to: 'games#leaderboard'
  get '/users/:id/history', to: 'users#history', as: 'user_history'
  resources :games
  resource :pizza_config
  resources :saved_orders
  resources :product, only: :show

  post '/product(/:id)', to: 'product#add_to_saved_order'
  get '/pizza', to: 'pizza_orders#new'
  post '/pizza', to: 'pizza_orders#create'
  get '/pizza/random', to: 'pizza_orders#random_order'
  get '/pizza/create', to: 'pizza_orders#create_pizza'
  get '/pizza/checkout', to: 'pizza_orders#checkout'
  get '/pizza/checkout_confirm', to: 'pizza_orders#checkout_confirm'
end

app/models/game.rb
class Game < ActiveRecord::Base

  require 'blinds_generator.rb'
  require 'name_generator.rb'

  has_many :players, dependent: :destroy
  before_destroy :remove_player_associations

  serialize :blinds, Array
  validates :chips, :game_length, :round_length, :blinds,
            :smallest_denomination, presence: true
  validates :chips, :round_length,
            :smallest_denomination, numericality: { only_integer: true, greater_than: 0 }
  validates :game_length, numericality: { greater_than: 0 }
  validate :round_not_longer_than_game
  validate :enough_players

  after_validation :generate_blinds, :generate_name, on: :create

  scope :in_progress, -> { where(complete: false) }
  scope :completed, -> { where(complete: true) }

  def find_player_by_owner(owner)
    if owner.class == User
      self.players.find {|player| player.user_id == owner.id}
    elsif owner.class == Guest
      self.players.find {|player| player.guest_id == owner.id}
    end
  end

  def players_out
    self.players.select {|player| player.winner == false}
  end

  def winner
    self.players.find {|player| player.winner == true}
  end

  def runner_up
    self.players_out.max_by {|player| player.position_out}
  end

  def number_of_players
    self.players.length
  end

  def total_chips
    self.chips * number_of_players
  end

  def set_player_out(player)
    player.winner = false
    player.round_out = self.round
    player.position_out = self.players_out.length
    player.save
    attempt_declare_winner
  end

  def attempt_declare_winner
    if self.players_out.length == self.number_of_players-1
      winner = (self.players - self.players_out)[0]
      winner.winner = true
      self.complete = true
      self.save
      winner.save
    end
  end

  protected

  def generate_blinds
    blinds_generator = BlindsGenerator.new(self)
    self.first_small_blind = blinds_generator.first_small_blind
    self.blinds = blinds_generator.blinds
    self.round_length = blinds_generator.round_length
  end

  def generate_name
    pokername = PokerName.new()
    self.name = pokername.name
  end

  def enough_players
    unless self.players.length > 1
      errors.add(:not_enough_players, "Specify at least 2 players")
    end
  end

  def round_not_longer_than_game
    unless self.round_length <= (self.game_length*60).to_i
      errors.add(:round_too_long, "Specify a round length less than or equal to your game length")
    end
  end

  def remove_player_associations
    self.players.each do |player|
      player.owner.players.delete(player.id)
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController


  before_action :require_login, :except => [:index, :show, :leaderboard, :archive]

  def index
    @games = Game.in_progress
    redirect_to new_game_path if @games.empty?
  end

  def show
    @game = Game.find(params[:id])
    @players = @game.players
    @blinds = @game.blinds.map {|small_blind| [small_blind, small_blind*2]}
    @current_blinds = @blinds[@game.round]

    respond_to do |format|
      format.html { render "show" }
      format.json { render json: @game }
    end
  end

  def new
    @game = Game.new
    @users = User.all
    @default_values = {
      game_length: 2.5,
      round_length: 15,
      chips: 2000,
      smallest_denomination: 1,
      first_small_blind: 1,
      buy_in: 10
    }
  end

  def edit
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.new(game_params)

    # Create the players as part of the game
    (params["game"]["guests"] || []).each do |guest|
      @game.players << Player.create(guest: Guest.find_or_create_by(name: guest))
    end
    (params["game"]["user_ids"] || []).each do |user|
      @game.players << Player.create(user: User.find(user))
    end

    if @game.save
      redirect_to game_path(@game)
    else
      flash[:alert] = @game.errors.full_messages
      redirect_to new_game_path
    end
  end

  def update
    game = Game.find(params[:id])

    if params[:game]
      # Mark a player out
      if player_out = params[:game][:player_out]
        player_out = game.players.detect {|player| player.id == player_out.to_i}
        game.set_player_out(player_out)
      end

      # Clear saved_timer if changing round_length
      if params[:game][:round_length] && game.saved_timer
        game.saved_timer = nil
      end

      # Order pizza
      if params[:game][:round] && params[:game][:round].to_i == game.order_pizza_after_round
        game.update_attribute(:order_pizza_after_round, nil)
        game.update_attributes(game_params)
        redirect_to saved_order_path(game.saved_order_id, game_id: game.id)
        return
      end

      game.update_attributes(game_params)
    end

    unless game.save
      flash[:alert] = game.errors.full_messages
    end

    respond_to do |format|
      format.html { redirect_to game_path(game) }
      format.json { render json: game }
    end
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to games_path
  end

  def archive
    @games = Game.completed.includes(:players => [:user, :guest])
  end

  def leaderboard
    require 'owner_stats.rb'
    @owner_stats = []
    (User.all.includes(:players) + Guest.all.includes(:players)).each do |owner|
      if owner.players.select {|player| !player.winner.nil?}.length > 0
        @owner_stats << OwnerStats.new(owner)
      end
    end
    @owner_stats.sort_by! {|stats| stats.win_perc }.reverse!
  end

  private
  def game_params
    params.require(:game).permit(:game_length, :round_length, :buy_in, :round, :name, :saved_timer,
                                 :chips, :first_small_blind, :smallest_denomination, :order_pizza_after_round, :saved_order_id)
  end

  def require_login
    unless user_signed_in?
      flash[:alert] = "You must log in to continue"
      redirect_to new_user_session_path
    end
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/archive.html.erb
<div class="container">
  <div class="span5 offset2">
    <div class="page-header">
      <h1>Archived Games</h1>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th>Game name</th>
          <th>Players</th>
          <th>Chips (per player)</th>
          <th>Length of game (hours)</th>
          <th>Winner</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @games.each do |game| %>
          <tr>
            <td><%= link_to game.name, game_path(game), class: "btn btn-default" %></td>
            <td><%= game.number_of_players %></td>
            <td><%= game.chips %></td>
            <td><%= game.game_length %></td>
            <td><%= game.winner.owner.name %></td>
            <% if user_signed_in? %>
              <td>
                <%= link_to "Delete Game", game_path(game), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/games/edit.html.erb
<div class="container">
  <div class="page-header span5 offset2">
    <h1>Edit game</h1>
  </div>
  <%= form_for(@game, html: {class: "form-horizontal"}) do |f| %>
    <div class="form-horizontal col-md-6">

      <% if @game.errors.any? %>
        <ul>
          <p>The game could not be updated for the following reasons:</p>
          <% @game.errors.each do |field, error| %>
            <li><%= field %></li>
          <% end %>
        </ul>
      <% end %>

      <div class="form-group">
        <%= f.label :name, "Name", class: "col-md-6 control-label" %>
        <div class="col-md-6 input-group">
          <%= f.text_field :name, class: "form-control"%>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :round_length, "Round length", class: "col-md-6 control-label" %>
        <div class="col-md-6 input-group">
          <%= f.number_field :round_length, class: "form-control" %>
          <div class="input-group-addon">min</div>
        </div>
      </div>

      <div class="col-md-offset-2 button-row">
        <%= f.submit "Update game", class: "btn btn-primary" %>
        <%= link_to "Back to game", game_path(@game), class: "btn btn-primary" %>
      </div>

    </div>
  <% end %>
</div>

app/views/games/index.html.erb
<div class="container">
  <div class="span5 offset2">
    <div class="page-header">
      <h1>In Progress Games</h1>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Game name</th>
          <th>Players</th>
          <th>Chips (per player)</th>
          <th>Length of game (hours)</th>
          <% if user_signed_in? %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @games.each do |game| %>
          <tr>
            <td><%= link_to game.name, game_path(game), class: "btn btn-default" %></td>
            <td><%= game.number_of_players %></td>
            <td><%= game.chips %></td>
            <td><%= game.game_length %></td>
            <% if user_signed_in? %>
              <td>
                <%= link_to "Delete Game", game_path(game), class: "btn btn-danger", method: :delete %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/games/leaderboard.html.erb
<div class="container">
  <div class="span5 offset2">
    <div class="page-header">
      <h1>All Time Wins</h1>
    </div>
    <table class="table" id="leaderboard">
      <thead>
        <tr>
          <th>Player <em>(* indicates guest)</em></th>
          <th>Number of Wins</th>
          <th>Win %</th>
        </tr>
      </thead>
      <tbody>
        <% @owner_stats.each do |stats| %>
          <tr>
            <td><%= stats.owner.name %><%= "*" if stats.owner.class == Guest %></td>
            <td><%= stats.games_won.length %></td>
            <td><%= stats.win_perc.round(2) %>%</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/games/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>Start a new game</h1>
  </div>
  <%= form_for(@game) do |f| %>
    <div class="form-horizontal col-md-6">

      <% if @game.errors.any? %>
        <ul>
          <p>The game could not be created for the following reasons:</p>
          <% @game.errors.each do |field, error| %>
            <li><%= field %></li>
          <% end %>
        </ul>
      <% end %>

      <div id="hiddenUsers"></div>

      <div class="form-group">
        <div class="col-md-offset-2">
          <button id="addUser" class="btn btn-primary" type="button">Add a User Player</button>
          <button id="addGuest" class="btn btn-primary" type="button">Add Guests</button>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :game_length, "Game length", class: "col-md-6 control-label" %>
        <div class="col-md-6 input-group">
          <%= f.number_field :game_length, class: "form-control", step: 0.05, value: @default_values[:game_length] %>
          <div class="input-group-addon">hrs</div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :round_length, "Target round length", class: "col-md-6 control-label" %>
        <div class="col-md-6 input-group">
          <%= f.number_field :round_length, class: "form-control", value: @default_values[:round_length] %>
          <div class="input-group-addon">min</div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :chips, "Chips per player", class: "col-md-6 control-label" %>
        <div class="col-md-6 input-group">
          <div class="input-group-addon">$</div>
          <%= f.number_field :chips, class: "form-control", value: @default_values[:chips] %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :smallest_denomination, "Smallest Denomination", class: "col-md-6 control-label" %>
        <div class="col-md-6 input-group">
          <div class="input-group-addon">$</div>
          <%= f.number_field :smallest_denomination, class: "form-control", value: @default_values[:smallest_denomination] %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :first_small_blind, "First Small Blind", class: "col-md-6 control-label" %>
        <div class="col-md-6 input-group">
          <div class="input-group-addon">$</div>
          <%= f.number_field :first_small_blind, class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :buy_in, "Buy In", class: "col-md-6 control-label" %>
        <div class="col-md-6 input-group">
          <div class="input-group-addon">$</div>
          <%= f.number_field :buy_in, class: "form-control", value: @default_values[:buy_in] %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :order_pizza_after_round, "Order Pizza (after round)", class: "col-md-6 control-label" %>
        <div class="col-md-6 input-group">
          <div class="input-group-addon">#</div>
          <%= f.number_field :order_pizza_after_round, class: "form-control", id: "order-pizza-round" %>
        </div>
      </div>

      <div class="form-group" id="order-select">
        <%= f.label :saved_order_id, "Pizza Order", class: "col-md-6 control-label" %>
        <div class="col-md-6 input-group">
          <%= f.select :saved_order_id, options_for_select(current_user.saved_orders.collect {|order| [order.name, order.id]}), {}, {class: "form-control"} %>
        </div>
      </div>

      <div class="col-md-offset-2 button-row">
        <%= f.submit "Create game", class: "btn btn-primary" %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <div id="userButtons">
          <% @users.each do |user| %>
            <div class="col-xs-3">
              <button type="button" class="btn btn-primary userButton" data-userid=<%= user.id %> data-username=<%= user.name %>><%= "Add #{user.name}" %></button>
            </div>
          <% end %>
          <div class="col-xs-3">
            <button type="button" class="btn btn-danger" id="userCancelButton">Done</button>
          </div>
        </div>
      </div>

      <div class="form-group" id="guestForm">
        <%= f.label :guests, "Guests (comma seperated)", class: "col-md-5 control-label" %>
        <div class="col-md-6">
          <input type="text" class="form-control" id="guestInput" />
        </div>
        <div class="col-md-1">
          <button type="button" class="btn btn-primary" id="guestSubmit">Submit</button>
        </div>
      </div>
    <% end %>

    <table class="table table-hover" id="players">
      <tr>
        <th>Players</th>
        <th></th>
      </tr>
    </table>
    </div>
</div>

app/views/games/show.html.erb
<div class="container">
  <div class="row">

    <audio id="clickAudio"><source src=<%= asset_path('click.ogg') %> type="audio/ogg" ></audio>
    <audio id="marimbaAudio"><source src=<%= asset_path('marimba.ogg') %> type="audio/ogg" ></audio>

    <div class="col-md-6">
      <div class="row" id="title-row">
        <div class="col-xs-6">
          <h1 id="gameTitle" data-gameid=<%= @game.id %>><%= @game.name %></h1>
        </div>
        <div class="col-xs-6">
          <h1 id="roundDisplay" data-roundid=<%= @game.round %>>Round <%= @game.round+1 %></h1>
        </div>
      </div>

      <% unless @game.complete || !user_signed_in? %>
        <div class="row button-row">
          <div class="col-xs-3">
            <button type="button" class="btn btn-primary" id="pauseTimer">Pause Timer</button>
            <button type="button" class="btn btn-primary" id="startTimer">Start Timer</button>
          </div>
          <div class="col-xs-3">
            <button type="button" class="btn btn-primary" id="nextRound">Next Round</button>
          </div>
          <div class="dropdown col-xs-3">
            <button class="btn btn-primary" type="button" id="roundSelect" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Go to round <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="roundSelect">
              <% @blinds.each_with_index do |blinds, i| %>
                <li><%= link_to "Round #{i+1} [#{blinds[0]} - #{blinds[1]}]", game_path(@game, :game => {round: i}),
                  method: :patch %></li>
              <% end %>
            </ul>
          </div>
          <div class="col-xs-3">
            <%= link_to "Edit Game", edit_game_path(@game), class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>

      <div class="row">
        <table class="table table-hover">
          <tr>
            <h3>Players</h3>
          </tr>
          <% @players.each do |player| %>
            <tr>
              <td><%= player.owner.name %></td>
              <td class="outButtonCell" data-playerid=<%= player.id %>>

                <% if player.round_out %>
                  <% if @game.runner_up == player %>
                    <%= "Runner up." %>
                    <td>
                      <%= " Earnings this game: $#{@game.buy_in}" %>
                    </td>
                  <% else %>
                    <%= "Out on round #{player.round_out+1}" %>
                    <% if @game.complete %>
                      <td></td>
                    <% end %>
                  <% end %>
                <% elsif @game.winner == player %>
                  <%= "Winner!" %>
                    <td>
                      <%= " Earnings this game: $#{@game.buy_in*(@game.number_of_players - 1)}" %>
                    </td>
                <% elsif user_signed_in? %>
                  <button type="button" class="btn btn-primary outButton" data-playerid=<%= player.id %>>Set Player Out</button>
                <% end %>

              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>

    <div class="col-md-6">
      <div class="timer-container">
        <h1 id="timer">
          <% if @game.complete %>
            Game Over
          <% end %>
        </h1>
      </div>

      <% if @game.complete %>
        <h3>Blind Structure</h3>
        <table class="table table-hover">
          <tr>
            <th>Round</th>
            <th>Small</th>
            <th>Big</th>
          </tr>
          <% @blinds.take(@game.round+2).each_with_index do |blinds, i| %>
          <tr>
            <td><%= i+1 %></td>
            <td><%= blinds[0] %></td>
            <td><%= blinds[1] %></td>
          </tr>
          <% end %>
        </table>
      <% else %>

        <div class="row">
          <div class="col-xs-6">
            <h2 class="blind">Small</h2>
            <h3 class="blind" id="smallBlind"><%= @current_blinds[0] %></h3>
          </div>
          <div class="col-xs-6">
            <h2 class="blind">Big</h2>
            <h3 class="blind" id="bigBlind"><%= @current_blinds[1] %></h3>
          </div>
        </div>
        <% upcoming_blinds = @blinds.select {|blind| blind[0] > @current_blinds[0]}.take(4) %>
        <% unless upcoming_blinds.empty? %>
          <table class="table table-hover" id="blindsTable">
            <tr>
              <h3>Upcoming Blinds</h3>
            </tr>
            <% upcoming_blinds.each do |small, big| %>
              <tr>
                <td><%= small %></td>
                <td><%= big %></td>
              </tr>
            <% end %>
          </table>
        <% end %>
      <% end %>

    </div>
  </div>
</div>