config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'games#index'
  get '/archive', to: 'games#archive'
  get '/leaderboard', to: 'games#leaderboard'
  get '/users/:id/history', to: 'users#history', as: 'user_history'
  resources :games
  resource :pizza_config
  resources :saved_orders
  resources :product, only: :show

  post '/product(/:id)', to: 'product#add_to_saved_order'
  get '/pizza', to: 'pizza_orders#new'
  post '/pizza', to: 'pizza_orders#create'
  get '/pizza/random', to: 'pizza_orders#random_order'
  get '/pizza/create', to: 'pizza_orders#create_pizza'
  get '/pizza/checkout', to: 'pizza_orders#checkout'
  get '/pizza/checkout_confirm', to: 'pizza_orders#checkout_confirm'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokerTracker</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <div id="container">
      <div class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'PokerTracker', root_url, class: "navbar-brand"%>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Statistics<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Leaderboard", leaderboard_path %></li>
                    <li><%= link_to "My History", user_history_path(current_user.id) %></li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Leaderboard", leaderboard_path %></li>
              <% end %>
              <% if Game.completed.any? || Game.in_progress.any? || user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Games<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <% if Game.in_progress.any? %>
                      <li><%= link_to "In Progress Games", games_path %></li>
                    <% end %>
                    <% if Game.completed.any? %>
                      <li><%= link_to "Archived Games", archive_path %></li>
                    <% end %>
                    <% if user_signed_in? %>
                      <li><%= link_to "New Game", new_game_path %></li>
                    <% end %>
                  </ul>
                </li>
              <% end %>
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pizza<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "See Pizza Orders", pizza_path %></li>
                    <li><%= link_to "My Pizza Config", pizza_config_path %></li>
                  </ul>
                </li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <% else %>
                <li><%= link_to "Sign Up", new_user_registration_path %></li>
                <li><%= link_to "Log In", new_user_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="container-fluid">
        <p class="bg-success" id="notice"><%= notice %></p>
        <p class="bg-warning" id="notice"><%= alert %></p>
        <%= yield %>
      </div>
    </div>
  </body>
</html>